# Generated by Django 2.2.1 on 2019-05-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190519_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contactNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectStatus',
            field=models.CharField(choices=[('active', 'Active'), ('incomplete', 'Incomplete'), ('complete', 'Complete')], default='active', max_length=15),
        ),
    ]
